### ISSUE TITLE
Dictionary data not updated since 2023-01-06

### ISSUE THREAD

**Issue by badboy** [mozilla/glean-dictionary#1576]
The dictionary currently says:

> Data last updated on [Friday, January 6, 2023](https://protosaur.dev/mps-deploys/). Built from revision [136276c0ab](https://github.com/mozilla/glean-dictionary/tree/136276c0ab21906dd4f4c29cd72a7e4365a74cfa).

We got successful schema deploys since then, so it's not clear why the dictionary doesn't have them.

**Comment by whd** [comment]
Here's a netlify build showing a failure: https://app.netlify.com/sites/glean-dictionary-prod/deploys/63bf61144bded200087e3218

Here are details on our Netlify setup, including who has access from DE to Netlify and how to request access: https://mozilla-hub.atlassian.net/wiki/spaces/SRE/pages/27919655/Netlify

Note that you might have read access to netlify via github without SSO if you have write access to this repo, I'm not 100% sure.

I checked for GCP credentials that might have been rotated and didn't find anything. This started failing before we removed the `python_moztelemetry` package from python so that's not the issue either.

I would guess the issue is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1809496 given the timing but would expect the problem to have resolved as of yesterday or so when I believe we entered a consistent state for the schemas pipeline.

Here's a relevant snippet of the netlify logs:

```
5:24:06 PM:   1. build.command from netlify.toml                            
5:24:06 PM: ────────────────────────────────────────────────────────────────
5:24:06 PM: ​
5:24:06 PM: $     set -e
5:24:06 PM:     pip install -e .
5:24:06 PM:     ./scripts/gd build-metadata
5:24:06 PM:     # glean.js currently requires a virtual environment
5:24:06 PM:     python -mvenv venv --without-pip
5:24:06 PM:     wget https://bootstrap.pypa.io/get-pip.py
5:24:06 PM:     venv/bin/python get-pip.py
5:24:06 PM:     venv/bin/pip install wheel
5:24:06 PM:     npm run build
5:24:06 PM:     if [ "$STORYBOOK" ]; then
5:24:06 PM:       npm run build-storybook
5:24:06 PM:       mv storybook-static public/storybook
5:24:06 PM:     fi
5:24:06 PM: 
5:24:06 PM: Obtaining file:///opt/build/repo
5:24:06 PM:   Installing build dependencies: started
5:24:09 PM:   Installing build dependencies: finished with status 'done'
5:24:09 PM:   Checking if build backend supports build_editable: started
5:24:09 PM:   Checking if build backend supports build_editable: finished with status 'done'
5:24:09 PM:   Getting requirements to build editable: started
5:24:09 PM:   Getting requirements to build editable: finished with status 'done'
5:24:09 PM:   Preparing editable metadata (pyproject.toml): started
5:24:09 PM:   Preparing editable metadata (pyproject.toml): finished with status 'done'
5:24:09 PM: Building wheels for collected packages: glean-dictionary
5:24:09 PM:   Building editable for glean-dictionary (pyproject.toml): started
5:24:09 PM:   Building editable for glean-dictionary (pyproject.toml): finished with status 'done'
5:24:09 PM:   Created wheel for glean-dictionary: filename=glean_dictionary-0.0.0-0.editable-py3-none-any.whl size=10219 sha256=ee3f2427cc05d1589baf6b6c06d4230469856344aa9a098af9e3b9f44c27c843
5:24:09 PM:   Stored in directory: /tmp/pip-ephem-wheel-cache-_c7w5y2w/wheels/15/ef/6d/5f6ef80dced486a1a3086ee2366a5097a79e53f92438567448
5:24:09 PM: Successfully built glean-dictionary
5:24:09 PM: Installing collected packages: glean-dictionary
5:24:10 PM: Successfully installed glean-dictionary-0.0.0
5:24:10 PM: WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.
5:24:10 PM: You should consider upgrading via the '/opt/buildhome/python3.8/bin/python -m pip install --upgrade pip' command.
5:24:18 PM: Traceback (most recent call last):
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/requests/models.py", line 910, in json
5:24:18 PM:     return complexjson.loads(self.text, **kwargs)
5:24:18 PM:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
5:24:18 PM:     return _default_decoder.decode(s)
5:24:18 PM:   File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
5:24:18 PM:     raise JSONDecodeError("Extra data", s, end)
5:24:18 PM: json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
5:24:18 PM: During handling of the above exception, another exception occurred:
5:24:18 PM: Traceback (most recent call last):
5:24:18 PM:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
5:24:18 PM:     return _run_code(code, main_globals, None,
5:24:18 PM:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
5:24:18 PM:     exec(code, run_globals)
5:24:18 PM:   File "/opt/build/repo/etl/__main__.py", line 33, in <module>
5:24:18 PM:     cli(obj={})
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
5:24:18 PM:     return self.main(*args, **kwargs)
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
5:24:19 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
5:24:18 PM:     rv = self.invoke(ctx)
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
5:24:18 PM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
5:24:18 PM:     return ctx.invoke(self.callback, **ctx.params)
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
5:24:18 PM:     return __callback(*args, **kwargs)
5:24:18 PM:   File "/opt/build/repo/etl/__main__.py", line 24, in build_metadata
5:24:18 PM:     write_glean_metadata(
5:24:18 PM:   File "/opt/build/repo/etl/glean_etl.py", line 268, in write_glean_metadata
5:24:18 PM:     bq_schema = requests.get(
5:24:18 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json
5:24:18 PM:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
5:24:18 PM: requests.exceptions.JSONDecodeError: [Errno Extra data] 404: Not Found: 3
5:24:18 PM: ​
5:24:18 PM:   "build.command" failed                                        
5:24:18 PM: ────────────────────────────────────────────────────────────────
5:24:18 PM: ​
5:24:18 PM:   Error message
5:24:18 PM:   Command failed with exit code 1:     set -e (https://ntl.fyi/exit-code-1)
5:24:18 PM:       pip install -e .
5:24:18 PM:       ./scripts/gd build-metadata
5:24:18 PM:       # glean.js currently requires a virtual environment
5:24:18 PM:       python -mvenv venv --without-pip
5:24:18 PM:       wget https://bootstrap.pypa.io/get-pip.py
5:24:18 PM:       venv/bin/python get-pip.py
5:24:18 PM:       venv/bin/pip install wheel
5:24:18 PM:       npm run build
5:24:18 PM:       if [ "$STORYBOOK" ]; then
5:24:18 PM:         npm run build-storybook
5:24:18 PM:         mv storybook-static public/storybook
5:24:18 PM:       fi
5:24:18 PM: ​​
5:24:18 PM:   Error location
5:24:18 PM:   In build.command from netlify.toml:
5:24:18 PM:       set -e
5:24:18 PM:       pip install -e .
5:24:18 PM:       ./scripts/gd build-metadata
5:24:18 PM:       # glean.js currently requires a virtual environment
5:24:18 PM:       python -mvenv venv --without-pip
5:24:18 PM:       wget https://bootstrap.pypa.io/get-pip.py
5:24:18 PM:       venv/bin/python get-pip.py
5:24:18 PM:       venv/bin/pip install wheel
5:24:18 PM:       npm run build
5:24:18 PM:       if [ "$STORYBOOK" ]; then
5:24:18 PM:         npm run build-storybook
5:24:18 PM:         mv storybook-static public/storybook
5:24:18 PM:       fi
5:24:18 PM: ​​
5:24:18 PM:   Resolved config
5:24:18 PM:   build:
5:24:18 PM:     command: |2
5:24:18 PM:           set -e
5:24:18 PM:           pip install -e .
5:24:18 PM:           ./scripts/gd build-metadata
5:24:18 PM:           # glean.js currently requires a virtual environment
5:24:18 PM:           python -mvenv venv --without-pip
5:24:18 PM:           wget https://bootstrap.pypa.io/get-pip.py
5:24:18 PM:           venv/bin/python get-pip.py
5:24:18 PM:           venv/bin/pip install wheel
5:24:18 PM:           npm run build
5:24:18 PM:           if [ "$STORYBOOK" ]; then
5:24:18 PM:             npm run build-storybook
5:24:18 PM:             mv storybook-static public/storybook
5:24:18 PM:           fi
5:24:18 PM:     commandOrigin: config
5:24:18 PM:     environment:
5:24:18 PM:       - GLEAN_APPLICATION_ID
5:24:18 PM:       - GLEAN_SOURCE_TAGS
5:24:18 PM:       - GOOGLE_ANALYTICS_ID
5:24:18 PM:       - INCOMING_HOOK_BODY
5:24:18 PM:       - INCOMING_HOOK_TITLE
5:24:18 PM:       - INCOMING_HOOK_URL
5:24:18 PM:       - POWERED_BY
5:24:18 PM:       - PYTHON_VERSION
5:24:18 PM:     publish: /opt/build/repo/public
5:24:18 PM:     publishOrigin: config
5:24:18 PM:   functionsDirectory: /opt/build/repo/.netlify
5:24:18 PM:   headers:
5:24:18 PM:     - for: /data/*
```

**Comment by badboy** [comment]
It's failing here: https://github.com/mozilla/glean-dictionary/blob/main/etl/glean_etl.py#L268-L271

Probably because it's trying to fetch a schema that doesn't exist.

**Comment by badboy** [comment]
It works fine for me locally.

**Comment by badboy** [comment]
The [last netlify build failure is from 2:24 AM](https://app.netlify.com/sites/glean-dictionary-prod/deploys/63c0b2d5a1b619000c0e020f), which (if that is in my local timezone) was 9 hours ago.

https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/6a2487b8984847237c2bccc126080604a95b497c landed at 2:26 and has additional bq files for firefox-desktop-background-update.

So maaaybe it's in a consistent state now?
I don't have permissions to retrigger a deploy so I'm looping in @edugfilho who should have those.

@edugfilho Can you re-trigger a deploy? If that still fails we might want to modify the `build-metadata` script to log a bit more so we know more precisely where it fails.

**Comment by badboy** [comment]
> Data last updated on [Monday, January 16, 2023](https://protosaur.dev/mps-deploys/). Built from revision [136276c0ab](https://github.com/mozilla/glean-dictionary/tree/136276c0ab21906dd4f4c29cd72a7e4365a74cfa).

As of today. So it seems it's working again and was caused by some of the other pipeline issues.
