### ISSUE TITLE
Dictionary deploy is failing

### ISSUE THREAD

**Issue by badboy** [mozilla/glean-dictionary#1600]
For the past 2 weeks the Glean Dictionary deploy has been failing:

```
2:30:12 AM: Traceback (most recent call last):
2:30:12 AM:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2:30:12 AM:     return _run_code(code, main_globals, None,
2:30:12 AM:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2:30:12 AM:     exec(code, run_globals)
2:30:12 AM:   File "/opt/build/repo/etl/__main__.py", line 33, in <module>
2:30:12 AM:     cli(obj={})
2:30:12 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
2:30:12 AM:     return self.main(*args, **kwargs)
2:30:12 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
2:30:12 AM:     rv = self.invoke(ctx)
2:30:12 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2:30:12 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2:30:12 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2:30:12 AM:     return ctx.invoke(self.callback, **ctx.params)
2:30:12 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2:30:12 AM:     return __callback(*args, **kwargs)
2:30:12 AM:   File "/opt/build/repo/etl/__main__.py", line 24, in build_metadata
2:30:12 AM:     write_glean_metadata(
2:30:12 AM:   File "/opt/build/repo/etl/glean_etl.py", line 231, in write_glean_metadata
2:30:12 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
2:30:12 AM:     for ping in app.get_pings():
2:30:12 AM:   File "/opt/build/repo/etl/glean.py", line 292, in get_pings
2:30:12 AM:     for ping_name, ping_data in self._get_ping_data().items()
2:30:12 AM:   File "/opt/build/repo/etl/glean.py", line 281, in _get_ping_data
2:30:12 AM:     GleanApp.PING_URL_TEMPLATE.format(dependency["v1_name"])
2:30:12 AM: TypeError: string indices must be integers
```

I'll look into this.

**Comment by badboy** [comment]
Above is the error from yesterday, that's fixed by changing it in probe-scraper.
There was another error the day before:

```
2:33:35 AM:     return self.main(*args, **kwargs)
2:33:35 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
2:33:35 AM:     rv = self.invoke(ctx)
2:33:35 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2:33:35 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2:33:35 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2:33:35 AM:     return ctx.invoke(self.callback, **ctx.params)
2:33:35 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2:33:35 AM:     return __callback(*args, **kwargs)
2:33:35 AM:   File "/opt/build/repo/etl/__main__.py", line 24, in build_metadata
2:33:35 AM:     write_glean_metadata(
2:33:35 AM:   File "/opt/build/repo/etl/glean_etl.py", line 268, in write_glean_metadata
2:33:35 AM:     bq_schema = requests.get(
2:33:35 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json
2:33:35 AM:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2:33:35 AM: requests.exceptions.JSONDecodeError: [Errno Extra data] 404: Not Found: 3
2:33:35 AM: ​
```

Not sure which URL it tried to load. We saw another schema rollout delay for some parts, maybe that's the same cause here.
Regardless, this didn't happen locally for me anymore.
