### ISSUE TITLE
Deploy 2023-03-22 failed

### ISSUE THREAD

**Issue by badboy** [mozilla/glean-dictionary#1635]
See https://app.netlify.com/sites/glean-dictionary-prod/deploys/641a5b98ed1b90000841aa1e

```
2:38:39 AM: Traceback (most recent call last):
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/requests/models.py", line 910, in json
2:38:39 AM:     return complexjson.loads(self.text, **kwargs)
2:38:39 AM:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
2:38:39 AM:     return _default_decoder.decode(s)
2:38:39 AM:   File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
2:38:39 AM:     raise JSONDecodeError("Extra data", s, end)
2:38:39 AM: json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
2:38:39 AM: During handling of the above exception, another exception occurred:
2:38:39 AM: Traceback (most recent call last):
2:38:39 AM:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2:38:39 AM:     return _run_code(code, main_globals, None,
2:38:39 AM:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2:38:39 AM:     exec(code, run_globals)
2:38:39 AM:   File "/opt/build/repo/etl/__main__.py", line 33, in <module>
2:38:39 AM:     cli(obj={})
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
2:38:39 AM:     return self.main(*args, **kwargs)
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
2:38:39 AM:     rv = self.invoke(ctx)
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2:38:39 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2:38:39 AM:     return ctx.invoke(self.callback, **ctx.params)
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2:38:39 AM:     return __callback(*args, **kwargs)
2:38:39 AM:   File "/opt/build/repo/etl/__main__.py", line 24, in build_metadata
2:38:39 AM:     write_glean_metadata(
2:38:39 AM:   File "/opt/build/repo/etl/glean_etl.py", line 268, in write_glean_metadata
2:38:39 AM:     bq_schema = requests.get(
2:38:39 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json
2:38:39 AM:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2:38:39 AM: requests.exceptions.JSONDecodeError: [Errno Extra data] 404: Not Found: 3
```

Possibly some new probe-scraper deployment missing some expected data?

**Comment by badboy** [comment]
It fixed itself and is now deployed.
